# Model Interation 2
Esta es la segunda iteracion del modelo. 

In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score, precision_score, recall_score, f1_score, 
    classification_report, confusion_matrix
)

# Cargar dataset
df = pd.read_csv('../Modelo/gamesWcategoricas.csv')

# Seleccionar features importantes
features_seleccionadas = [
    'Average playtime forever', 'Median playtime forever', 'Release date',
    'tag_action', 'tag_adventure', 'tag_early_access', 'tag_indie', 'tag_casual',
    'tag_strategy', 'tag_simulation', 'tag_singleplayer', 'Average playtime two weeks',
    'tag_design_&_illustration', 'Median playtime two weeks', 'Peak CCU',
    'tag_multiplayer', 'tag_fighting'
]

# Variables predictoras y objetivo
X = df[features_seleccionadas]
y = df['Estimated owners']  # Ajustar si tiene otro nombre


/var/folders/yn/vbht61m97rg6wrrbgs95_9k00000gn/T/ipykernel_90460/498205623.py:14: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../Modelo/gamesWcategoricas.csv')


### Split, escalado y entrenamiento del modelo

In [ ]:
# División en train/test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Escalado
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Entrenamiento del modelo
model = LogisticRegression(
    max_iter=1000,
    multi_class='multinomial',
    solver='lbfgs'
)
model.fit(X_train_scaled, y_train)

# Predicciones
y_pred_iter2 = model.predict(X_test_scaled)


/Users/luisvillela/Desktop/UFM/2025-1/Data science/ProyectoDataScience/env/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


# Evaluación del modelo de Iteración 2

In [8]:
from sklearn.metrics import (
    classification_report, precision_score,
    recall_score, f1_score, confusion_matrix
)
from scipy.stats import ks_2samp


# Matriz de Confusión
cm = confusion_matrix(y_test, y_pred_iter2)
print("Matriz de Confusión (Iteración 2):")
print(cm)

# Reporte general
print("\nReporte de Clasificación:")
print(classification_report(y_test, y_pred_iter2))

# Métricas macro y weighted
print("Precision (macro):", round(precision_score(y_test, y_pred_iter2, average='macro'), 3))
print("recall (macro):", round(recall_score(y_test, y_pred_iter2, average='macro'), 3))
print("F1 Score (macro):", round(f1_score(y_test, y_pred_iter2, average='macro'), 3))

print("Precision (weighted):", round(precision_score(y_test, y_pred_iter2, average='weighted'), 3))
print("Recall (weighted):", round(recall_score(y_test, y_pred_iter2, average='weighted'), 3))
print("F1 Score (weighted):", round(f1_score(y_test, y_pred_iter2, average='weighted'), 3))

# 1. Crear versión binaria del target para KS
threshold = 100000
y_test_bin = (y_test >= threshold).astype(int)

# 2. Obtener índice de la clase positiva en predict_proba
clase_positiva = model.classes_[np.argmax(model.classes_ >= threshold)]
indice_clase = list(model.classes_).index(clase_positiva)

# 3. Probabilidades predichas para esa clase
y_prob = model.predict_proba(X_test_scaled)[:, indice_clase]

# 4. Separar según valor real
probs_pos = y_prob[y_test_bin == 1]
probs_neg = y_prob[y_test_bin == 0]

# 5. KS Score
ks_score = ks_2samp(probs_pos, probs_neg).statistic
print("KS Score:", round(ks_score, 3))


Matriz de Confusión (Iteración 2):
[[ 4008   425     1     0     0     0     0     0     0     0     0     0]
 [ 2300 11599    86     7     3    21     0     0     0     0     0     0]
 [    2  1534   110     5     9    33     0     0     0     0     0     0]
 [    0   651    88     7     7    38     1     1     0     0     0     0]
 [    0   378    97     7     8    58     3     0     1     0     0     0]
 [    0   221    78     6     4   101     5     5     2     0     0     0]
 [    0    52    32     0     1    62    15    12     5     1     1     0]
 [    0    23    16     1     0    44    18    14     1     0     0     0]
 [    0     0     2     1     0    24    14    14     3     1     1     0]
 [    0     1     1     1     0     7     1     1     1     0     1     0]
 [    0     0     0     0     0     1     3     1     1     0     0     0]
 [    0     0     0     1     0     0     0     0     1     0     0     1]]

Reporte de Clasificación:
              precision    recall  f1