# Model Interation 1
Esta es la primera iteracion del modelo. 

In [ ]:
# Imports
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, precision_score, recall_score, f1_score, confusion_matrix
from scipy.stats import ks_2samp
import matplotlib.pyplot as plt
import seaborn as sns

# Cargar dataset
df = pd.read_csv('../Modelo/gamesWcategoricas.csv')

# Ingeniería de features
df['release_year'] = df['Release date']
def clasificar_precio(precio):
    if precio == 0:
        return 'free'
    elif precio < 10:
        return 'low'
    elif precio < 30:
        return 'medium'
    else:
        return 'high'
df['price_range'] = df['Price'].apply(clasificar_precio)
df_encoded = pd.get_dummies(df, columns=['price_range'], prefix='price')

# eparar X e y
X = df_encoded.drop(columns=['Estimated owners'])
y = df_encoded['Estimated owners']
X = X.drop(columns=X.select_dtypes(include='object').columns)

# Split + Escalado
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Modelo
model = LogisticRegression(
    max_iter=1000,
    multi_class='multinomial',
    solver='lbfgs',
    C=0.5,
    class_weight='balanced'
)
model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

# Evaluación
print("Matriz de Confusión:")
print(confusion_matrix(y_test, y_pred))

print("\nReporte de Clasificación:")
print(classification_report(y_test, y_pred, digits=3))

print("Precision (macro):", round(precision_score(y_test, y_pred, average='macro'), 3))
print("Recall (macro):", round(recall_score(y_test, y_pred, average='macro'), 3))
print("F1 Score (macro):", round(f1_score(y_test, y_pred, average='macro'), 3))
print("Precision (weighted):", round(precision_score(y_test, y_pred, average='weighted'), 3))
print("Recall (weighted):", round(recall_score(y_test, y_pred, average='weighted'), 3))
print("F1 Score (weighted):", round(f1_score(y_test, y_pred, average='weighted'), 3))

# KS Score
threshold = 100000
y_test_bin = (y_test >= threshold).astype(int)
clase_positiva = model.classes_[np.argmax(model.classes_ >= threshold)]
indice_clase = list(model.classes_).index(clase_positiva)
y_prob = model.predict_proba(X_test_scaled)[:, indice_clase]
probs_pos = y_prob[y_test_bin == 1]
probs_neg = y_prob[y_test_bin == 0]
ks_score = ks_2samp(probs_pos, probs_neg).statistic
print("KS Score:", round(ks_score, 3))


/var/folders/yn/vbht61m97rg6wrrbgs95_9k00000gn/T/ipykernel_91840/143770121.py:13: DtypeWarning: Columns (18) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../Modelo/gamesWcategoricas.csv')
/Users/luisvillela/Desktop/UFM/2025-1/Data science/ProyectoDataScience/env/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


📌 Matriz de Confusión:
[[4254  163   11    5    1    0    0    0    0    0    0    0    0    0]
 [1711 8819 2515  639  224   56   16   18   10    5    2    1    0    0]
 [   2  397  713  359  152   49    9    7    1    2    2    0    0    0]
 [   0  111  232  201  173   49   16    8    1    2    0    0    0    0]
 [   0   28  104   94  174   97   35   11    6    1    0    1    0    1]
 [   0    9   26   40   84  157   71   28    4    3    0    0    0    0]
 [   0    2    3    6   10   49   66   26   14    4    1    0    0    0]
 [   0    1    2    2    3   13   32   38   16    7    3    0    0    0]
 [   0    0    0    0    0    1    6   20   23    8    1    1    0    0]
 [   0    0    0    0    0    0    1    0    9    2    1    0    1    0]
 [   0    0    0    0    0    1    0    0    3    1    0    0    1    0]
 [   0    0    0    0    0    0    0    0    0    1    0    2    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0]
 [   0    0    0    0    0  

/Users/luisvillela/Desktop/UFM/2025-1/Data science/ProyectoDataScience/env/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/luisvillela/Desktop/UFM/2025-1/Data science/ProyectoDataScience/env/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/Users/luisvillela/Desktop/UFM/2025-1/Data science/ProyectoDataScience/env/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_